"use client";
import Sidebar from "@/components/Sidebar";

export default function TermsPage() {
  return (
    <div className="flex min-h-screen w-full flex-col lg:flex-row">
      <Sidebar />
      <main className="flex-1 min-w-0 overflow-x-hidden px-4 py-6 sm:px-8 sm:py-8">
        <header className="mb-6">
          <h1 className="text-2xl font-semibold text-slate-100 light:text-slate-900">Terms &amp; Conditions</h1>
          <p className="mt-1 text-xs text-slate-500">Effective date: 7 August 2026</p>
        </header>
        <div className="card p-6 space-y-5 text-sm text-slate-300 light:text-slate-700 leading-relaxed">
          <div>
            <h2 className="font-semibold text-amber-400 text-base mb-1">1. About the Service</h2>
            <p>
              Vidhi Mitra ("the Platform") is owned and operated by Divya Sewa CSC Kendra (CSC ID: 511236470017),
              Haldwani, Uttarakhand, India ("we", "us", "our"). By accessing or using the Platform (website or mobile
              app), you agree to these Terms &amp; Conditions.
            </p>
          </div>
          <div>
            <h2 className="font-semibold text-amber-400 text-base mb-1">2. No Legal Advice / Disclaimer</h2>
            <p>The drafts, research summaries, and citations generated by this platform are produced with the assistance of automated/AI tools and do not constitute formal legal advice. They are provided strictly for informational, educational, and drafting-assistance purposes only.</p>
          </div>
          <div>
            <h2 className="font-semibold text-amber-400 text-base mb-1">3. User Verification</h2>
            <p>Users must independently verify all generated content, case laws, facts, and legal provisions with a qualified advocate or legal professional before filing them in any court or using them in official proceedings.</p>
          </div>
          <div>
            <h2 className="font-semibold text-amber-400 text-base mb-1">4. Eligibility &amp; Account Use</h2>
            <p>You must be at least 18 years old, or use the Platform under the supervision of a CSC operator/guardian, to use paid or drafting features. You are responsible for the accuracy of the information you enter.</p>
          </div>
          <div>
            <h2 className="font-semibold text-amber-400 text-base mb-1">5. Fees &amp; Payments</h2>
            <p>Certain features are chargeable on a pay-per-draft or wallet-recharge basis, processed through third-party payment gateways. See our <a href="/refund" className="text-amber-300 underline">Refund &amp; Cancellation Policy</a> for details.</p>
          </div>
          <div>
            <h2 className="font-semibold text-amber-400 text-base mb-1">6. Limitation of Liability</h2>
            <p>The creators, developers, and operators of this platform shall not be held liable for any direct, indirect, incidental, or consequential damages arising out of the use, misuse, or inability to use the platform or its generated content.</p>
          </div>
          <div>
            <h2 className="font-semibold text-amber-400 text-base mb-1">7. Privacy &amp; Data Security</h2>
            <p>We respect your privacy. See our <a href="/privacy" className="text-amber-300 underline">Privacy Policy</a> for how your data is collected, used, and stored, in line with the Digital Personal Data Protection Act, 2023 (DPDP Act).</p>
          </div>
          <div>
            <h2 className="font-semibold text-amber-400 text-base mb-1">8. Governing Law &amp; Jurisdiction</h2>
            <p>These Terms are governed by the laws of India. Any disputes shall be subject to the exclusive jurisdiction of the courts at Haldwani, Uttarakhand.</p>
          </div>
          <div>
            <h2 className="font-semibold text-amber-400 text-base mb-1">9. Grievance Officer / Contact</h2>
            <p>
              For any complaints, disputes, or grievances regarding the Platform, please contact:<br />
              Rajendra Kumar Arya (Rajendra Nath) , Divya Sewa CSC Kendra (CSC ID: 511236470017)<br />
              Email: rajenderarya340@gmail.com · Phone: +91 92589 82833<br />
              Haldwani, Uttarakhand, India
            </p>
          </div>
        </div>
      </main>
    </div>
  );
}