"use client";
import Sidebar from "@/components/Sidebar";

export default function TermsPage() {
  return (
    <div className="flex min-h-screen w-full">
      <Sidebar />
      <main className="flex-1 px-8 py-8">
        <header className="mb-6">
          <h1 className="text-2xl font-semibold text-slate-100 light:text-slate-900">Terms & Conditions</h1>
        </header>
        <div className="card p-6 space-y-5 text-sm text-slate-300 light:text-slate-700 leading-relaxed">
          <div>
            <h2 className="font-semibold text-amber-400 text-base mb-1">1. No Legal Advice / Disclaimer</h2>
            <p>The drafts, research summaries, and citations generated by this platform are powered by Artificial Intelligence and do not constitute formal legal advice. They are provided strictly for informational, educational, and drafting assistance purposes only.</p>
          </div>
          <div>
            <h2 className="font-semibold text-amber-400 text-base mb-1">2. User Verification</h2>
            <p>Users must independently verify all generated content, case laws, facts, and legal provisions with a qualified advocate or legal professional before filing them in any court or using them in official proceedings.</p>
          </div>
          <div>
            <h2 className="font-semibold text-amber-400 text-base mb-1">3. Limitation of Liability</h2>
            <p>The creators, developers, and operators of this platform shall not be held liable for any direct, indirect, incidental, or consequential damages arising out of the use, misuse, or inability to use the platform or its generated content.</p>
          </div>
          <div>
            <h2 className="font-semibold text-amber-400 text-base mb-1">4. Privacy & Data Security</h2>
            <p>We respect your privacy. Any sensitive client data entered into the drafting studio is processed temporarily for generation purposes and is not permanently stored or used to train public AI models.</p>
          </div>
        </div>
      </main>
    </div>
  );
}
